site_name: 北京印刷学院 ACM-ICPC 集训队官方网站
theme:
  name: material
  font: false
  palette:
  - media: (prefers-color-scheme)
    toggle:
      icon: material/brightness-auto
      name: Auto
  - scheme: default
    primary: teal
    accent: purple
    media: "(prefers-color-scheme: light)"
    toggle:
      icon: material/weather-sunny
      name: Light Mode
  - scheme: slate
    primary: black
    accent: lime
    media: "(prefers-color-scheme: dark)"
    toggle:
      icon: material/weather-night
      name: Dark Mode

nav:
  - 首页: index.md
  - 贡献: CONTRIBUTING.md
  - 历年成绩: results.md
  - 成员信息: members.md
  - 集训队章程: rules.md
  - 25招新: join-us/index.html
  - 2025 新生训练计划: 
      - 组队: 2025 新生训练计划/teams.md
      - 讲座安排: 2025 新生训练计划/lectures.md
      - 训练安排: 2025 新生训练计划/training.md
      - 新生赛: 2025 新生训练计划/contest.md
  - 面向零基础萌新的 ACM 入门指南: quickstart.md
  - Jetbrains学生许可证申请: Jetbrains/Jetbrains学生许可证申请流程.md
markdown_extensions:
  - pymdownx.tilde